#!/bin/bash

GREEN="`tput setaf 2`"
YELLOW="`tput setaf 3`"
MAGENTA="`tput setaf 5`"
CYAN="`tput setaf 6`"
WHITE="`tput setaf 7`"

echo " "
echo "${WHITE}Enter App Name"
echo "${YELLOW}>"
read app_name

mkdir -p $app_name/{images,scripts}
cd $app_name
echo " "
echo "${CYAN}Directories created..."

touch manifest.json
cat > manifest.json <<EOF
{ 
    "account_code_blocks": 
    [
    {
        "code": "",
        "name": "",
        "content": "",
        "placement_code": "",
        "description": ""
    }
    ],

    "config_fields": 
    [
    {
        "code": "_textbox_example",
        "name": "textbox_example",   
        "label": "textbox example",
        "ordinal": 0,
        "category": "",
        "control_type": "textbox",
        "scopes": "",
        "description": "",
    },
    {
        "code": "_toggle_example",
        "name": "toggle_example",   
        "label": "toggle example",
        "ordinal": 1,
        "category": "",
        "control_type": "toggle",
        "scopes": "",
        "description": "",
    },
    {
        "code": "_number_example",
        "name": "number_example",   
        "label": "number example",
        "ordinal": 2,
        "category": "",
        "control_type": "number",
        "scopes": "",
        "description": "",
    }
    ]
}
EOF

echo "Manifest populated..."
echo " "

echo "${WHITE}Enter git repository URL for initial commit "
echo "${YELLOW}>"
read git_url
echo " "

touch README.md
echo "${CYAN}README.md created...${MAGENTA}"

git init
git add .
git commit -m "Initial commit"
git remote add origin $git_url
git push -u origin master

echo " "
echo "${CYAN}Changes pushed..."
echo " "
echo "${GREEN}Happy developing (<>..<>)"
echo " "
